trigger:
  - master
pool:
  vmImage: 'ubuntu-latest'
stages:
  - stage: 'stageOne'
    jobs:
       - job: "myjob"
  - stage: 'stageTwo'
    jobs:
       - job: 'myJob'
    condition: failed()
  - stage: 'stageThree'
    jobs:
       - job: 'myjob'
    condition: succeeded()
  - stage: 'stageFour'
    jobs: 
      - job: 'myjob'
    dependsOn: 
    - stageOne
    - stageTwo