trigger:
- main  # Adjust to your branch

pool:
  vmImage: ubuntu-latest

steps:
# Step 1: Install Docker and Docker Compose (if needed)
- task: DockerInstaller@0
  displayName: 'Install Docker'

- script: |
   sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
   sudo chmod +x /usr/local/bin/docker-compose
   docker-compose --version
  displayName: 'Install Docker Compose'


# Step 2: Build and run containers using docker-compose
- script: |
    docker-compose up -d # Start services in detached mode
  displayName: 'Run docker-compose'

