trigger:
  - master
pool:
  vmImage: 'ubuntu-latest'
stages:
  - stage: 'stageOne'
    jobs:
      - job: 'myJob'
        steps:
          - task: Docker@1
          - script: cd frontend && docker build -t my-frontend .
      - job: 'mineJob'
        steps: 
          - task: Docker@1
          - script: cd backend && docker build -t my-backend .
        dependsOn: myJob
      - job: 'hisJob'
        steps:
          - task: DockerCompose@1
          - script: docker-compose up -d
        dependsOn: mineJob