# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- my-files

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    export NODE_OPTIONS=--openssl-legacy-provider
    cd frontend
    npm install
    npm start
    npm build
  displayName: 'npm install and run for frontend'
  
- script: |
    cd backend
    npm install
    nodejs index.js
    npm build
  displayName: 'npm install and run for backend'