trigger:
  - master
pool:
  vmImage: 'ubuntu-latest'
stages:
  - stage: 'buildstage'
    jobs:
      - job: 'myjob'
        steps:
           - script: echo "ubuntu machine is running here"
  - stage: 'deploystage'
    pool:
      vmImage: 'windows-latest'
    jobs:
      - job: 'myjob'
        steps:
          - script: echo "windows machine is running here"