trigger:
- main  # Adjust to the branch or files you want to monitor

pool:
  vmImage: ubuntu-latest

variables:
  frontend_dir: 'frontend'
  backend_dir: 'backend'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

# Frontend build steps
- script: |
    cd $(frontend_dir)
    npm install
    npm run build
  displayName: 'Install dependencies and build frontend'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(frontend_dir)/build'
    ArtifactName: 'frontend'
  displayName: 'Publish frontend build artifacts'

# Backend build steps
- script: |
    cd $(backend_dir)
    npm install
    npm test
    npm run build
  displayName: 'Install dependencies, test, and build backend'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(backend_dir)'
    ArtifactName: 'backend'
  displayName: 'Publish backend build artifacts'
