trigger:
  - master
pool:
  vmImage: 'ubuntu-latest'
stages:
  - stage: 'stageOne'
    jobs:
      - job: 'myJob'
        steps:
          - task: Docker@1
          - script: cd backend
          - script: docker build -t my-backend .
          - task: Docker@1
          - script: cd frontend
                    docker build -t my-frontend .
          - task: DockerCompose@1
          - script: docker-compose up -d