trigger:
  - master
pool:
  vmImage: 'macOS-latest'
stages:
  - stage: 'mystage'
    jobs:
       - job: 'myjob1'
         steps:
           - script: echo "macOS is working "
       - job: 'myjob2'
         pool:
           vmImage: 'windows-latest'
         steps:
           - script: echo "windows is working"