trigger:
- main  # Adjust to your branch

pool:
  vmImage: ubuntu-latest

steps:
# Step 1: Install Docker and Docker Compose (if needed)
- task: DockerInstaller@0
  displayName: 'Install Docker'

- script: |
    mkdir -p ~/.docker/cli-plugins/
    curl -SL https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-linux-x86_64 -o ~/.docker/cli-plugins/docker-compose
    chmod +x ~/.docker/cli-plugins/docker-compose
    docker compose version
  displayName: 'Install Docker Compose'


# Step 2: Build and run containers using docker-compose
- script: |
    docker compose up -d # Start services in detached mode
  displayName: 'Run docker-compose'

