trigger:
  - master

stages:
  - stage: A 
    jobs:
    - job: 'one'
      steps:
        - script: echo "hii this is first job"
    - job: 'second'
      steps:
        - script: echo "hi this is second job"
           