version: "3.8"
services:
  web:
    build: .
    depends_on:
      - api
    ports:
      - "3000:3000"
    networks:
      - network-backend
  api:
    build: .
    depends_on:
      - mongo
    ports:
      - "3001:3001"
    networks: 
     - network-backend
  
  mongo:
    image: mongo
    restart: always
    env_file:
      - .env
    networks: 
     - network-backend

networks:
  network-backend:
